### PR TITLE
I added the video link to the CHAOSS working groups

### PR DESCRIPTION
**Pull request by frontEndDoctor**

### CODE REVIEW

**Comment by peculiaruc** [comment]
Hi @geekygirldawn could you please review this? Thank you

**Review by geekygirldawn — APPROVED** [review]
@frontEndDoctor Thank you so much for recording the video! I noticed one mistake in the video - OSPO stands for Open Source Program Office (it sounded like maybe you said public office?), but I think that's a minor enough mistake that I wouldn't necessarily re-record it unless you wanted to. It's hard to make a 6+ minute video without any mistakes :)

**Comment by peculiaruc** [comment]
@frontEndDoctor  Thanks so much. Let me know when you will be free for the recording so I can book a slot for you.
We normally use Fridays and Mondays or Weekends, Anyone that works for you.

**Comment by peculiaruc** [comment]
I will be re-assigning this issue, thanks @frontEndDoctor  for your effort in working on this

**Pull request closed without merging**
