### PR TITLE
Update Submission.md

### PR DESCRIPTION
**Pull request by AbdessamadTzn**
Open Source in Education, I added the script to submission file

### CODE REVIEW

**Comment by AbdessamadTzn** [comment]
Open Soutrc ein education - Scripts

**Comment by peculiaruc** [comment]
> Open Soutrc ein education - Scripts

Thank you for your contribution. Kindly give me access to your doc.

**Comment by AbdessamadTzn** [comment]
Hello, sorry I didn't pay attention, I submitted an updated link.
Kind regards,

**Comment by peculiaruc** [comment]
> Hello, sorry I didn't pay attention, I submitted an updated link. Kind regards,

Hi @AbdessamadTzn this is the sample of what i asked for https://docs.google.com/document/d/1n4hyVelssmNEKrtwnD-bgKbpdKhd2KR4xurpis08pZM/edit. 
this will help us to add comments or suggestions while reviewing the Script

**Comment by peculiaruc** [comment]
@AbdessamadTzn  Kindly adjusted the Script to include everyone. 
The  focus is not on Africa. The focus should be on everyone that is interested in open source.

**Review by peculiaruc — APPROVED** [review]

**Comment by AbdessamadTzn** [comment]
@geekygirldawn @peculiaruc I have adjusted the Script, as described in your notes, can you re-check please if you can see the changes?

**Comment by peculiaruc** [comment]
Thanks, @AbdessamadTzn,  for your effort in working on this issue. 
We would like you to remove examples referring to Africa only.    Also, add a general reference with links.

**Pull request closed without merging**
