### PR TITLE
I added the script for the Open Source Licensing issue

### PR DESCRIPTION
**Pull request by Aysha-py**
#95

### CODE REVIEW

**Comment by peculiaruc** [comment]
Thanks a lot for this PR. Review is ongoing

**Review by peculiaruc — APPROVED** [review]

**Comment by peculiaruc** [comment]
@Aysha-py  You might need to look at the script again to ensure this can be recorded between 5 -10 mins. where that will not be possible, I am suggesting we trim the script a little bit.

**Comment by peculiaruc** [comment]
Hi @Aysha-py this PR is having a merge conflict. We can close it and create a new one or Fix the merge conflict

**Comment by Aysha-py** [comment]
I will resolve the conflict on my end and revert back @peculiaruc

**Comment by Aysha-py** [comment]
@peculiaruc , the conflicts is resolved. Thank you

**Comment by peculiaruc** [comment]
> @peculiaruc , the conflicts is resolved. Thank you

Awesome!

**Pull request merged**
